version: "3.5"

services:
  snowflake-proxy:
    build: .
    image: "snowflake.public.dappnode.eth:0.1.0"
    restart: unless-stopped
    environment:
      EXTRA_OPTS: ""
    ports:
      - "30000-30999:30000-30999/udp"
